name: admin
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1


environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Utils
  connectivity_plus: ^6.0.5
  dartz: ^0.10.1

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3

  intl: ^0.19.0
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  meta: ^1.15.0
  get_it: ^8.0.1
  flutter_secure_storage: ^9.2.2
  data_table_2: ^2.5.15
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/content/user/
    - assets/images/animations/
    - assets/icons/payment_methods/

  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800

